Todo/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Todo.Utils;

namespace Todo.Controllers
{
    public class ContactController : Controller
    {
		public IActionResult Index()
		{
			//Session
			var nu = HttpContext.Session.Get<int>("tellertje");
			return Content("en vanaf contact staat hij nu op " + nu + " en de tempdata teller op: " + TempData["tellertje2"]);
		}
	}
}

Todo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Todo.DataAccess;
using Todo.Utils;

namespace Todo.Controllers
{
	public class HomeController : Controller
	{
		private ITodoContext context;

		public HomeController(ITodoContext context)
		{
			this.context = context;
		}

		public IActionResult Index()
		{
			ViewData["bla"] = "<script>alert('yay');</script>";
			return View(context.Todos.ToList());
		}

		public IActionResult Ophoog()
		{
			var nu = HttpContext.Session.Get<int>("tellertje");
			HttpContext.Session.Set<int>("tellertje", nu + 1);

			TempData["tellertje2"] = nu + 1;

			return Content("teller staat nu op " + (nu + 1));
		}

		[HttpPost]
		public IActionResult Index(TodoModel newTodo)
		{
			if (ModelState.IsValid)
			{
				context.Todos.Add(newTodo);
				context.SaveChanges();
			}

			return View(context.Todos.ToList());
		}

		public IActionResult GetData()
		{
			return Json(context.Todos.ToArray());
		}
	}
}

Todo/ViewComponents/TodoFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Todo.DataAccess;

namespace Todo.ViewComponents
{
	public class TodoFormViewComponent : ViewComponent
	{
		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View(new TodoModel() { Task = "Bla" });
		}
	}
}

Todo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Todo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Todo/Views/Home/Index.cshtml
@model List<Todo.DataAccess.TodoModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <h1>Todo-app 3</h1>
</div>

<div class="row">

    <div class="col-lg-6">
        <h2>Todos</h2>

		Injection: @Html.Raw(ViewData["bla"])

        <ul>
            @foreach(var item in Model)
            {
                <li>@item.Task</li>
            }
        </ul>
    </div>
    <div class="col-lg-5 col-lg-offset-1">
        <h2>Todo toevoegen</h2>

        <vc:todo-form></vc:todo-form>
    </div>
</div>

Todo/Views/Home/Index.mobile.cshtml
@model List<Todo.DataAccess.TodoModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <h1>Mobiele todo-app</h1>
</div>

<div class="row">

    <div class="col-lg-6">
        <h2>Todos</h2>

        <ul>
            @foreach(var item in Model)
            {
                <li>@item.Task</li>
            }
        </ul>
    </div>
    <div class="col-lg-5 col-lg-offset-1">
        <h2>Todo toevoegen</h2>

        <vc:todo-form></vc:todo-form>
    </div>
</div>

Todo/Views/Shared/Components/TodoForm/Default.cshtml
@model Todo.DataAccess.TodoModel

En dit is de default view van de todoform. Wat magisch in 1 keer gaat werken. Ongetwijfeld.

@using (Html.BeginForm())
{
    <ul>
        <li>
            @Html.LabelFor(x => x.Task)
            @Html.EditorFor(x => x.Task)
			@Html.ValidationMessageFor(x => x.Task)
        </li>
        <li>
            @Html.LabelFor(x => x.DueDate)
            @Html.EditorFor(x => x.DueDate)
			@Html.ValidationMessageFor(x => x.DueDate)
        </li>
        <li>
            <button>Submit</button>
        </li>
    </ul>
}

Todo/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Todo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Todo</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
		<script src="~/js/jquery.naampje-validator.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
		<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
		<script src="~/js/jquery.naampje-validator.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>